# Generated by Django 3.1.7 on 2021-08-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='postalCode',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
