# Generated by Django 3.1.7 on 2021-08-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('dateAdded', models.DateField(auto_now=True)),
                ('longitude', models.CharField(max_length=30, null=True)),
                ('lattitude', models.CharField(max_length=30, null=True)),
                ('postalCode', models.IntegerField(null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
